spring:
    application:
        name: myjournal
    # the following properties are used for setting up the local mongodb server port to the project.
    # spring.data.mongodb.host=localhost
    # spring.data.mongodb.port=27017
    # the following propert is used for connecting to mongodb atlas
    data:
        mongodb:
            # 1. ENVIRONMENT-AWARE CONNECTION STRING:
            # Spring looks for a system environment variable named 'MONGODB_ATLAS_URI' (e.g., in VS Code launch.json or AWS env properties).
            # If found, it connects to your live Cloud Atlas Cluster. 
            # If absent, the ':' acts as an OR switch, falling back to a local database instance at 'mongodb://localhost:27017'.
            uri: ${MONGO_ATLAS_URI:mongodb://localhost:27017}
            database: journaldb
            auto-index-creation: true
# Enables automatic creation of indexes defined in your Entity classes.
# Without this set to 'true', the @Indexed(unique = true) annotation in your UserEntity will be ignored by Spring Data MongoDB.
server:
    port: 8081