spring:
    application:
        name: myjournal
    # the following properties are used for setting up the local mongodb server port to the project.
    # spring.data.mongodb.host=localhost
    # spring.data.mongodb.port=27017
    # the following propert is used for connecting to mongodb atlas
    data:
        mongodb:
            uri: mongodb+srv://jkv9963_db_user:WKskR1JejEatdiO4@cluster0.ssbkead.mongodb.net/?appName=Cluster0
            database: journaldb
            auto-index-creation: true
# Enables automatic creation of indexes defined in your Entity classes.
# Without this set to 'true', the @Indexed(unique = true) annotation in your UserEntity will be ignored by Spring Data MongoDB.
server:
    port: 8080