spring.application.name=myJournal
# the following properties are used for setting up the local mongodb server port to the project.
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=journaldb